name: exchats
description: ExChats Mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  provider: ^6.0.2

  intl: ^0.18.1
  shared_preferences: ^2.0.13
  flutter_svg: ^2.0.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile/
    - assets/profile/bussines/
    - assets/bottom/
    - assets/auth/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf