name: exchats
description: ExChats Mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.1.1
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  go_router: ^17.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  flutter_svg: ^2.0.15
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0
  environment_config: ^3.2.0
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/core/assets/gen
  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/profile/
    - assets/profile/bussines/
    - assets/bottom/
    - assets/auth/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
